### ISSUE TITLE
Elignment wrong in Atom 1.13.0

### ISSUE THREAD

**Issue by lillem4n** [hax/atom-elastic-tabstops#11]
See screenshot
![screenshot from 2017-01-16 14-06-49](https://cloud.githubusercontent.com/assets/281230/21984237/4d4f7e1c-dbf5-11e6-8e18-3cefed195736.png)

**Comment by lillem4n** [comment]
x64 on Linux if that is an issue...

**Comment by lillem4n** [comment]
I've added a $100 bounty for anyone who fixes this: https://www.bountysource.com/issues/41003894-elignment-wrong-in-atom-1-13-0 :)

**Comment by hax** [comment]
Oops, it seems something changed in last Atom update. I will try to investigate it soon.

**Comment by hax** [comment]
A new version has been released. If still problem pls let me know.

**Comment by lillem4n** [comment]
Do not forget to pick up the $100 from bountysource :)
