### ISSUE TITLE
Atom@1.12.4 失效

### ISSUE THREAD

**Issue by francislee-cn** [hax/atom-elastic-tabstops#8]
如题，已禁用所有其他插件，并重启Atom，新建一个test.js也没有效果

**Comment by hax** [comment]
请确定你的窗口被识别为使用 tab，对于被识别为 space 的不会生效。通常设置里的Tab Type、Soft Tabs等选项会影响结果。

**Comment by francislee-cn** [comment]
感谢！检查设置后确认是“Soft Tabs”影响到了插件运行。
Solution: Settings->Editor->Soft Tabs -> Uncheck
