### ISSUE TITLE
Deprecated selector in `elastic-tabstops/styles/elastic-tabstops.less`

### ISSUE THREAD

**Issue by brunocruzcoelho** [hax/atom-elastic-tabstops#9]
In `elastic-tabstops/styles/elastic-tabstops.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow span.hard-tab` => `atom-text-editor.editor span.hard-tab`

* `atom-text-editor::shadow span.hard-tab.indent-guide:first-child` => `atom-text-editor.editor span.hard-tab.indent-guide:first-child`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by hax** [comment]
PR is welcome!
